# TEXPANEL — deployed & configured
name = "texpanel"
main = "worker.js"
compatibility_date = "2026-08-25"
workers_dev = true
account_id = "2c3b7070a7da77f2486b276c38fd013b"

[[d1_databases]]
binding = "DB"
database_name = "texpanel"
database_id = "d5f3db73-1860-4beb-a3a0-693423527f2c"

[[kv_namespaces]]
binding = "KV"
id = "718a75b9e36c436a87df3ff0ba6a43f8"
